SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

LOAD DATA INFILE '' INTO TABLE ICD10_Ref 
CHARACTER SET utf8mb4 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (code, description);

LOAD DATA INFILE '' INTO TABLE KEN_Ref 
CHARACTER SET utf8mb4 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (code, base_cost, mdn_days);

LOAD DATA INFILE '' INTO TABLE Active_Substances 
CHARACTER SET utf8mb4 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (id, substance_name);

LOAD DATA INFILE '' INTO TABLE Medications 
CHARACTER SET utf8mb4 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (id, product_name);

LOAD DATA INFILE 'LabExam_Ref.csv' INTO TABLE LabExam_Ref 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (code, name, type);

LOAD DATA INFILE 'MedicalAct_Ref.csv' INTO TABLE MedicalAct_Ref 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (code, name, category);

SET FOREIGN_KEY_CHECKS = 1;